### ISSUE TITLE
[Epic] Upgrade .NET 8

### ISSUE THREAD

**Issue by leo-schick** [kapok-fwk/kapok-fwk#12]
Kapok Framework tries to keep on track of the newest .NET LTS version. The current LTS is 6.0, but next will be 8. In this ticket I will collect tasks which I plan to do while / during upgrading to .NET 8:

* [ ] upgrade all libraries to enforce .NET 8 or higher
* [ ] use EF Core 8.0, which includes
    * [ ] using null propagation for strings  (since 7.0)
* [ ] replace package `Newtonsoft.Json` with `System.Text.Json` (according to [this blog post](https://medium.com/@tobias.streng/net-performance-series-2-newtonsoft-vs-system-text-json-2bf43e037db0) `System.Text.Json` is twice as fast as the popular `Newtonsoft.Json` package since at least .NET 7.0)
